---
title: "Human Resources/ Employee Satisfaction Report"
author: "Joshua Kober"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: flatly
runtime: shiny
---



<style>                     
.navbar {
  background-color:lightsteelblue;
  border-color:Black;
}
.navbar-brand {
color:Black!important;
}
</style>




```{r setup, include=FALSE}
#Download packages needed for this report
library(dplyr)
library(viridisLite)
library(forecast)

library(flexdashboard)
library(shiny)

library(readr)


library(plotly)
library(ggplot2)
library(ggthemes)
library(leaflet)
library(dplyr)
library(knitr)

library(DT)

library(magrittr)

library(stringr)


#Read in data for those who quit
#setwd("~/Stat 281")
quitters=read.csv('EmployeeSatisfactionProject.csv',header=T,stringsAsFactors = F)

```


```{r}
#function to retrieve the mode for character data
mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```


```{r}
#function to retrieve state abbreviations
stateFromUpper <-function(x) {
  #read 52 state codes into local variable [includes DC (Washington D.C. and PR (Puerto Rico)]
  st.codes<-data.frame(
    state=as.factor(c("alaska","alabama","arkansas","arizona","california","colorado",
                      "connecticut","district of columbia","delaware","florida","georgia",
                      "hawaii","iowa","idaho","illinois","indiana","kansas","kentucky",
                      "louisiana","massachusetts","maryland","maine","michigan","minnesota",
                      "missouri","mississippi","montana","north carolina","north dakota",
                      "nebraska","new hampshire","new jersey","new mexico","nevada",
                      "new york","ohio","oklahoma","oregon","pennsylvania","puerto rico",
                      "rhode island","south carolina","south dakota","tennessee","texas",
                      "utah","virginia","vermont","washington","wisconsin",
                      "west virginia","wyoming",'guam','virgin islands')),
    full=as.factor(c("AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
                     "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME",
                     "MI", "MN", "MO", "MS",  "MT", "NC", "ND", "NE", "NH", "NJ", "NM",
                     "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN",
                     "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY",'GU','VI'))
  )
  #create an nx1 data.frame of state codes from source column
  st.x<-data.frame(state=x)
  #match source codes with codes from 'st.codes' local variable and use to return the full state name
  refac.x<-st.codes$full[match(st.x$state,st.codes$state)]
  #return the full state names in the same order in which they appeared in the original source
  return(refac.x)
  
}
```



```{r input_panel}
sidebarPanel( 
  
#Insert the filter inputs
  selectInput("department", label = "Select the Department",selected='All', 
            c('All',quitters$department)),
  selectInput("salary", label = "Select the Salary Category",selected='All', 
            c('All',quitters$salary)),
  numericInput("careermonths", 
              label = "Months with Company Minimum",
              value=min(quitters$time_spend_company_months), 
            min(quitters$time_spend_company_months), 
            max(quitters$time_spend_company_months)),
  width = 2
)

```

Dashboard {data-orientation=columns}
===================================================

column {data-width=700}
-----------------------------------------------------------------------


```{r}
df_input <- reactive({
  
  #Apply filters on the data
  if(input$department!='All'){
    filterQuitters<-subset(quitters,quitters$department==input$department)
  }else{
    filterQuitters=quitters
  }
  if(input$salary!='All'){
    filterQuitters=subset(filterQuitters,filterQuitters$salary==input$salary)
  }
  
    filterQuitters=subset(filterQuitters,
                          filterQuitters$time_spend_company_months>=input$careermonths)
  
  
  return(filterQuitters)
})  
```  


### Dashboard

```{r}
renderPlotly({
  #Graph satisfaction level of all and those who left by filtered data
  newQuitters<-df_input()
  #Aquire evaluation for all the employees
  newQuitters$count<-rep(1,nrow(newQuitters))
  newQuitters$satisfaction_level<-round(newQuitters$satisfaction_level,2)
  allaverage<-round(mean(newQuitters$satisfaction_level),2)
  allsd<-round(sd(newQuitters$satisfaction_level),2)
  all<-aggregate(count~satisfaction_level,data=newQuitters,sum)
  
  #Aquire evaluation for those who left
  left<-subset(newQuitters,newQuitters$left==1)
  leftaverage<-round(mean(left$satisfaction_level),2)
  leftsd<-round(sd(left$satisfaction_level),2)
  left<-aggregate(count~satisfaction_level,data=left,sum)
  all<-merge(all,left,by='satisfaction_level',all=T)
  colnames(all)<-c('SatisfactionLevels','AllCount','LeftCount')
  all$AllCount<-ifelse(is.na(all$AllCount),0,all$AllCount)
  all$LeftCount<-ifelse(is.na(all$LeftCount),0,all$LeftCount)
  
  plot_ly(all,x=~SatisfactionLevels,y=~AllCount, name = 'All Employees',mode = 'lines+markers')%>%
    add_trace(y=~AllCount, name = 'All Employees', mode = 'lines+markers')%>%
     add_trace(y=~LeftCount, name = 'Employees Who Quit', mode = 'lines+markers')%>%
     add_trace(y=c(0,(max(all$AllCount))),
               x=c(allaverage+(1.96*(allsd/sqrt(sum(all$AllCount)))),allaverage+(1.96*(allsd/sqrt(sum(all$AllCount))))),
               name='Upper Satisfaction Of All',mode='lines',line=list(color='DarkBlue'))%>%
    add_trace(y=c(0,(max(all$AllCount))),
               x=c(allaverage-(1.96*(allsd/sqrt(sum(all$AllCount)))),allaverage-(1.96*(allsd/sqrt(sum(all$AllCount))))),
               name='Lower Satisfaction Of All',mode='lines',line=list(color='DarkBlue'))%>%
    add_trace(y=c(0,(max(all$AllCount))),
               x=c(leftaverage+(2.575*(leftsd/sqrt(sum(all$LeftCount)))),leftaverage+(2.575*(leftsd/sqrt(sum(all$LeftCount))))),
               name='Upper Satisfaction Of Those Who Left',mode='lines',line=list(color='Orange'))%>%
    add_trace(y=c(0,(max(all$AllCount))),
               x=c(leftaverage-(2.575*(leftsd/sqrt(sum(all$LeftCount)))),leftaverage-(2.575*(leftsd/sqrt(sum(all$LeftCount))))),
               name='Lower Satisfaction Of Those Who Left',mode='lines',line=list(color='Orange'))%>%
    layout(title='Employee Satisfaction Levels 99% Confidence Interval')
})
```

### Percentage of Those who Quit By Department

```{r}
renderPlotly({
  #Graph the percentage of those who leave by department
  newQuitters<-df_input()
  departmentLeave<-aggregate(left~department,data=newQuitters,mean)
     plot_ly(departmentLeave,x=~department,y=~1-left, name = 'Those Who Stayed',type='bar')%>%
    add_trace(y=~left, name = 'Those Who Left', type='bar')%>%
    layout(title='Percentage of those Who Left By Department')
})  
```

column {.tabset data-width=300}
-----------------------------------------------------------------------

### Stats

```{r}
DT::renderDataTable({
  #Create table of statistics for the filtered data
  all<-df_input()
  stay<-subset(all,all$left==0)
  go<-subset(all,all$left==1)
  stats<-data.frame(Description=c('Total Employees',
                                  'Total Quit',
                                  'Stayed Avg Monthly Hours',
                                  'Quitters Avg Monthly Hours',
                                  'Stayed Avg Number of Projects',
                                  'Quitters Avg Number of Projects',
                                  'Stayed Salary at',
                                  'Quitters Salary at',
                                  "Stayed Work Accidents Percentage",
                                  "Quitter Work Accidents Percentage"),
                    Stat=c(nrow(all),
                           nrow(go),
                           mean(stay$average_monthly_hours),
                           mean(go$average_monthly_hours),
                           mean(stay$number_project),
                           mean(go$number_project),
                           mode(stay$salary),
                           mode(go$salary),
                           sum(stay$Work_accident)/nrow(stay),
                           sum(go$Work_accident)/nrow(go)))
  DT::datatable(stats, rownames = FALSE, filter = 'top', extensions = 'Buttons',
                  options = list(
    pageLength = 100, autoWidth = TRUE,dom = 'Bfrtip',
    buttons = c('copy','csv','print')
    ))
                    
                    
  
})  
```

Further Analysis { data-orientation=columns}
===================================================

### Decision Tree on Likelihood of an Employee Leaving

```{r}

renderPlot({
  main=df_input()
  
  
  
  library(rpart)  # Contains decision tree functions we want to use
  #library(rattle)  # Used to make nice-looking representation of decision tree
  library(rpart.plot)  # Used to make nice-looking representation of decision tree
  library(RColorBrewer)  # Used to make nice-looking representation of decision tree
    
    
  #tree<-main  
  
  
  
  
  
  # Make a training set: a step to assess overfit
  set.seed(14)
  train<-sample(1:nrow(main),nrow(main)*.5)
  train.data<-main[train,]
  
  
  
  # grow tree 
  
    fit <- rpart(left~ .,
                data=train.data)

  # Make a more graphically pleasing image
    
    rpart.plot(fit,tweak=.8,cex = 1)
    
})
```

### March 2018 Unemployment USA Map

```{r,fig.width=12,fig.height=10}
renderPlotly({
  #Graph the percentage of those who leave by department
  unemployment<-read.csv('UnemploymentStateRates.csv',header=T,stringsAsFactors = F, encoding = 'UTF-8', fileEncoding = 'ISO8859-1')
  colnames(unemployment)<-c('State','Rate')
  unemployment$State<-as.character(unemployment$State)
  unemployment$State=tolower(unemployment$State)
 
  library(maps)
 unemployment=fortify(unemployment, region="State")
  map <- map_data("state")
  unemployment$group=as.factor(gsub(' ','',paste(unemployment$State,'.1')))
  map$group=as.factor(gsub(' ','',paste(map$region,'.1')))
  
  

  
  
  
  
  
  
j<-ggplot(unemployment,aes(group=Rate,fill=Rate))
ggplotly(j + geom_map(aes(map_id = State), map = map)+
           theme_map() +
           expand_limits(x = map$long, y = map$lat,group=map$group)+
           scale_fill_gradient(low='seagreen',high='red'))
  
})  
```


### Another Map

```{r}


renderPlotly({
   unemployment<-read.csv('UnemploymentStateRates.csv',header=T,stringsAsFactors = F, encoding = 'UTF-8', fileEncoding = 'ISO8859-1')
  colnames(unemployment)<-c('State','Rate')
  unemployment$State=tolower(unemployment$State)
  unemployment$State=stateFromUpper(unemployment$State)
  unemployment$State<-as.character(unemployment$State)
 
  zip<-data.frame(state=unique(zipcode$state),rank=rep(1,length(unique(zipcode$state))))
  
  plot_ly(zip,type="choropleth", locations=zip$state, locationmode="USA-states", z=zip$rank) %>% layout(geo=list(scope="usa"))

})




```



